---
- hosts: all
  become: yes
  vars:
    workspace: /home/vagrant
    ansible_ssh_user: vagrant
  pre_tasks:
    - name: Install tools & libs
      apt: "name={{ item }} state=present"
      with_items:
        - git
        - htop
        - libpq-dev
  roles:
    - role: rvm_io.rvm1-ruby
      rvm1_install_flags: '--auto-dotfiles --user-install'
      rvm1_install_path: '/home/{{ ansible_ssh_user }}/.rvm'
      rvm1_user: '{{ ansible_ssh_user }}'
      rvm1_rubies:
        - 'ruby-2.3.1'
    - role: geerlingguy.nodejs
      nodejs_version: "4.x"
      nodejs_install_npm_user: "{{ ansible_ssh_user }}"
    - role: ANXS.postgresql
      postgresql_users:
        - name: "vagrant"
      postgresql_user_privileges:
        - name: "vagrant"
          db: "postgres"
          priv: "ALL"
          role_attr_flags: "CREATEDB"
  tasks:
    - name: CD to workdir after login
      lineinfile: dest=/home/vagrant/.profile line='cd /vagrant'
