AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - db/schema.rb
    - bin/*
    - vendor/bundle/**/*
    - provision/**/*

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
